export const constants = {
    backRN : /\r\n/,
    newLineChar : '\n',
    comma: ',',
    period: '.',
    allNonAlph: /\W/g,
    backR: /\r/,
    backN: /\n/,
    backT: /\t/,
    backB: /\b/,
    backF: /\f/,
    empty: '',
    space: ' ',
    one: 1,
    a: 'a',
    sliceBeginZero: 0,
    sliceEndTwenty: 20,
    onlyAlph: /^[a-zA-Z]+$/,
    notAlph: /[^a-zA-Z]/g 
}